package com.baidubce.face.models;

import com.baidubce.common.BaseBceRequest;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class FaceMergeRequest extends BaseBceRequest {

    /**
    * 服务版本，可选1.0/2.0/3.0/4.0，默认1.0。推荐2.0融合效果，3.0清晰度更高，4.0为最新版本
    */
    private String version;

    /**
    * 融合参数，范围0-1浮点数，保留两位小数，默认0，仅version=4.0时有效。0代表与目标图最大程度相似，1代表完全保留模版图
    */
    private Float alpha;

    /**
    * 模板图信息，JSON对象，包含image（BASE64或FACE_TOKEN）、image_type（必填）、quality_control（可选）、face_location（可选）
    */
    @JsonProperty("image_template")
    private String imageTemplate;

    /**
    * 目标图信息，JSON对象，包含image（BASE64/URL/FACE_TOKEN）、image_type（必填）、quality_control（可选）、face_location（可选）
    */
    @JsonProperty("image_target")
    private String imageTarget;

    /**
    * 融合度，越高则融合图与目标图越相似
    */
    @JsonProperty("merge_degree")
    private String mergeDegree;

    /**
    * 水印位置：0-右下角，1-左下角，2-左上角，3-右上角，默认0
    */
    private Integer position;

    /**
    * 水印语言：0-中文（AI生成），1-英文（Generated by AI），默认0
    */
    private Integer language;

    public String getVersion() {
        return version;
    }

    public FaceMergeRequest setVersion(String version) {
        this.version = version;
        return this;
    }

    public Float getAlpha() {
        return alpha;
    }

    public FaceMergeRequest setAlpha(Float alpha) {
        this.alpha = alpha;
        return this;
    }

    public String getImageTemplate() {
        return imageTemplate;
    }

    public FaceMergeRequest setImageTemplate(String imageTemplate) {
        this.imageTemplate = imageTemplate;
        return this;
    }

    public String getImageTarget() {
        return imageTarget;
    }

    public FaceMergeRequest setImageTarget(String imageTarget) {
        this.imageTarget = imageTarget;
        return this;
    }

    public String getMergeDegree() {
        return mergeDegree;
    }

    public FaceMergeRequest setMergeDegree(String mergeDegree) {
        this.mergeDegree = mergeDegree;
        return this;
    }

    public Integer getPosition() {
        return position;
    }

    public FaceMergeRequest setPosition(Integer position) {
        this.position = position;
        return this;
    }

    public Integer getLanguage() {
        return language;
    }

    public FaceMergeRequest setLanguage(Integer language) {
        this.language = language;
        return this;
    }

}
